<?php

namespace app\models;

use app\core\Application;
use app\core\db\DbModel;
use PDO;
use app\core\Model;


class ChildWeight extends DbModel
{
    public string $weight_record_id ='';
    public string $child_id = '';
    public string $value_of_weight ='';

    public function rules(): array
    {
        return[

            'value_of_weight'=> [self::RULE_REQUIRED],
            'child_id'=> [self::RULE_REQUIRED]

        ];
    }

    public function tableName(): string
    {
        return 'ChildWeight';
    }

    public function primaryKey(): string
    {
        return 'weight_record_id';
    }

    public function attributes(): array
    {
        return [
            'value_of_weight',
            'child_id'
        ];
    }
    public function getWeight(): string
    {
        $child_id = $this->getChildId();
        $WeightData = (new ChildWeight())->findAll(self::class,['child_id'=>$child_id]);
        $data = [];

        foreach ($WeightData as $Weight) {
            $data[] = [
                'Date' => $Weight->Date,
                'Count' => $Weight->weight_record_id
            ];
        }
        return json_encode($data);
    }

    public function getChildId()
    {
        $UserId = Application::$app->user->getId();
        $ChildData = self::findOne(Child::class, ['user_id' => $UserId]);
        return "1";
    }

    public function save(): bool
    {
        $this->child_id = $this->getChildId();
        return parent::save(); // TODO: Change the autogenerated stub
    }

    public function isNew(): bool
    {
        $Tdy_rec= ChildWeight::findOneByChildIdAndDate(ChildWeight::class);
        return empty($Tdy_rec);
    }
    static public function findOneByChildIdAndDate($modelClass)
    {
        $tableName = (new $modelClass())->tableName();
        $currentDate = date("Y-m-d"); // Get the current date in the "YYYY-MM-DD" format
        $childId = (new ChildWeight())->getChildId();

        $sql = "child_id = :childId AND DATE_FORMAT(Time, '%Y-%m-%d') = :currentDate";

//        $sql->bindValue(":motherId", $motherId);
//        $sql->bindValue(":currentDate", $currentDate);

        $statement = self::prepare("SELECT * FROM $tableName WHERE $sql");

        $statement->bindValue(":childId", $childId);
        $statement->bindValue(":currentDate", $currentDate);

        $statement->execute();

        return $statement->fetchObject(static::class);
    }
}
